apiVersion: v1
kind: Pod
metadata:
  #
  # This is the name that will appear in kubectl get po
  #
  name: busybox1
  labels:
    app: busybox
    foo : bar
spec:
  #
  # The specification is a list of attributes, one of which
  # is the list of containers
  # 
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command:
      - /bin/sh
    args:
      - -c
      - echo hi
    imagePullPolicy: IfNotPresent
