apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    #
    # In this case we're using a single command and no args.
    # the command is in alternate YAML list notation
    #
    command: [/bin/sh, -c, 'while true; do echo $(date); sleep 1; done']
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
