apiVersion: apps/v1
#
# Create a deployment ( https://kubernetes.io/docs/concepts/workloads/controllers/deployment/ )
#
kind: Deployment
metadata:
  name: blog-deployment
spec:
  replicas: 3
  # The .spec.selector field defines how the Deployment finds which Pods to manage.
  # In this case, you simply select a label that is defined in the Pod template (app: blog).
  # However, more sophisticated selection rules are possible,
  # as long as the Pod template itself satisfies the rule.
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: dirkcgrunwald/blog
        ports:
        - containerPort: 8888
        env:
          - name: FLASK_PORT
            value: "8888"